 export const STACK_NAVIGATOR_SCREENS = {
    //unAuthScreens
    ONBOARDINGSCREEN: "ONBOARDINGSCREEN",
    LOGINSCREEN: "LOGINSCREEN",
    REGISTERSCREEN: "REGISTERSCREEN",
    QUESTIONNAIRESCREEN: "QUESTIONNAIRESCREEN",

    //authScreens
    MAINFLOWS: "MAINFLOWS",
    PARTNERSCREEN: "PARTNERSCREEN",
    FINDLOCATIONSCREEN: "FINDLOCATIONSCREEN",
    MATCHLOCATIONSCREEN: "MATCHLOCATIONSCREEN",
    INFORMATIONSCREEN: "INFORMATIONSCREEN",
    WORKSPACEDOCTORSCREEN: "WORKSPACEDOCTORSCREEN",
    DOCTORDETAILSCREEN: "DOCTORDETAILSCREEN",
    MYHEALTHSCREEN: "MYHEALTHSCREEN",
    EDITWORKPROFILESCREEN: "EDITWORKPROFILESCREEN",
    TRACKINGHEALTHSCREEN: "TRACKINGHEALTHSCREEN",
    SCHEDULESCREEN: "SCHEDULESCREEN",
    APPOINTMENTSCREEN: "APPOINTMENTSCREEN",
    APPOINTMENTDETAILSCREEN: "APPOINTMENTDETAILSCREEN",
    MYSCHEDULESCREEN: "MYSCHEDULESCREEN",
    PAYMENTSCREEN: "PAYMENTSCREEN",
    WEBVIEWSCREEN: "WEBVIEWSCREEN",
    TESTSCREEN: "TESTSCREEN",
    SERVICESCREEN: "SERVICESCREEN",
    SERVICEDETAILSCREEN: "SERVICEDETAILSCREEN",
    CHANGEPASSWORDSCREEN: "CHANGEPASSWORDSCREEN",
  };

  export const BOTTOM_NAVIGATOR_SCREENS = {
    HOMESCREEN: "HomeScreen",
    COMMUNITYSCREEN: "CommunityScreen",
    DOCTORSCREEN: "DoctorScreen",
    PROFILESCREEN: "ProfileScreen",
  };
  
  